language: php
php:
  - '7.0'
script:
  - composer install
  - ./vendor/bin/phpunit

# Tell Travis CI to monitor only 'master' branch
branches:
  only: master

# You can delete cache using travis-ci web interface
cache:
  directories:
  - vendor
  - $HOME/.cache/composer